---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8800, host: 8080}]
    - ["forwarded_port", {guest: 5000, host: 5000}]
provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: recipe[docker_registry::install]
    attributes:
